// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bktjyiyqiwiwlgprqyyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdGp5aXlxaXdpd2xncHJxeXlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODQ5MjQsImV4cCI6MjA1NzU2MDkyNH0.VNnBvdYzGGENI1Q_qFWAUp6kiubCmWbfCctuqNqVqug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);